version: "3.8"

services:
  postgres:
    container_name: ms_pg_sql
    image: postgres:17.6
    environment:
      POSTGRES_USER: venom
      POSTGRES_PASSWORD: venom
      POSTGRES_DB: ecommerce
    command: [ "postgres" ]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U venom -d ecommerce" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4:9.6
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - microservices-net
    restart: unless-stopped


  mongo:
    container_name: ms_mongo_db
    image: mongo:8.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--username",
          "admin",
          "--password",
          "admin",
          "--authenticationDatabase",
          "admin",
          "--eval",
          "db.adminCommand('ping')"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - microservices-net
    restart: unless-stopped


  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express:1.0.2
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"
    networks:
      - microservices-net
    restart: unless-stopped


  zookeeper:
    container_name: ms_zookeeper
    image: confluentinc/cp-zookeeper:7.8.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - microservices-net
    restart: unless-stopped


  kafka:
    container_name: ms_kafka
    image: confluentinc/cp-kafka:7.8.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9092:9092"
    networks:
      - microservices-net
    restart: unless-stopped


  maildev:
    container_name: ms_mail_dev
    image: maildev/maildev:2.2.1
    ports:
      - "1080:1080"  # Web UI
      - "1025:1025"  # SMTP
    networks:
      - microservices-net
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:3.5.1
    restart: unless-stopped
    ports:
      - "9411:9411"
    networks:
      microservices-net:


  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.3.2
    command: [ "start-dev", "--http-port=8089" ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      microservices-net:
    ports:
      - "8089:8089"


  config-server:
    build: ./config-server
    container_name: config-server
    restart: unless-stopped
    ports:
      - "8888:8888"
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - microservices-net



  eureka-discovery:
    build: ./eureka-discovery
    container_name: eureka-discovery
    restart: unless-stopped
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - microservices-net

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    restart: unless-stopped
    ports:
      - "8222:8222"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-discovery:
        condition: service_healthy
    networks:
      - microservices-net



  customer-service:
    build: ./customer-service
    restart: unless-stopped
    depends_on:
      config-server:
        condition: service_healthy
      eureka-discovery:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    networks:
      - microservices-net


  order-service:
    build: ./order-service
    restart: unless-stopped
    depends_on:
      config-server:
        condition: service_healthy
      eureka-discovery:
        condition: service_healthy
    networks:
      - microservices-net

  payment-service:
    build: ./payment-service
    restart: unless-stopped
    depends_on:
      config-server:
        condition: service_healthy
      eureka-discovery:
        condition: service_healthy
    networks:
      - microservices-net

  stock-service:
    build: ./stock-service
    restart: unless-stopped
    depends_on:
      config-server:
        condition: service_healthy
      eureka-discovery:
        condition: service_healthy

    networks:
      - microservices-net


  notification-service:
    build: ./notification-service
    restart: unless-stopped
    depends_on:
      config-server:
        condition: service_healthy
      eureka-discovery:
        condition: service_healthy
    networks:
      - microservices-net





networks:
  microservices-net:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  mongo_data: