spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@mongo:27017/customer?authSource=admin

  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: OrderConfirmation:com.example.ecommerce.kafka.order.OrderConfirmation


server:
  port: 8090

management:
  tracing:
    sampling:
      probability: 1.0

zipkin:
  tracing:
    endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://eureka-discovery:8761/eureka
