spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false

      routes:

        # Swagger / OpenAPI routes

        - id: customer-swagger
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/v3/api-docs
          filters:
            - RewritePath=/customer/v3/api-docs, /v3/api-docs

        - id: order-swagger
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/v3/api-docs
          filters:
            - RewritePath=/order/v3/api-docs, /v3/api-docs

        - id: stock-swagger
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/stock/v3/api-docs
          filters:
            - RewritePath=/stock/v3/api-docs, /v3/api-docs

        - id: payment-swagger
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/v3/api-docs
          filters:
            - RewritePath=/payment/v3/api-docs, /v3/api-docs



        # Application API routes


        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**

        - id: order-lines-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-lines/**

        - id: stock-service
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/api/v1/stocks/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**


server:
  port: 8222



# Swagger / OpenAPI


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Customer Service
        url: /customer/v3/api-docs

      - name: Order Service
        url: /order/v3/api-docs

      - name: Stock Service
        url: /stock/v3/api-docs

      - name: Payment Service
        url: /payment/v3/api-docs




management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

  endpoint:
    gateway:
      enabled: true

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans


eureka:
  client:
    service-url:
      defaultZone: http://eureka-discovery:8761/eureka