server:
  port: 8040

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@mongo:27017/notifications?authSource=admin

  mail:
    host: maildev
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://eureka-discovery:8761/eureka