server:
  port: 8040

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@127.0.0.1:27018/notifications?authSource=admin

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: true
        spring.json.trusted.packages: com.example.ecommerce.*
        # Optional: explicit alias mapping (no trailing commas)
        spring.json.type.mapping: >
          OrderConfirmation:com.example.ecommerce.kafka.order.OrderConfirmation,
          PaymentNotificationRequest:com.example.ecommerce.kafka.payment.PaymentNotificationRequest

  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000
