spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?options=-c%20TimeZone=Asia/Kolkata
    username: venom
    password: venom
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET TIME ZONE 'Asia/Kolkata'
      connection-test-query: SELECT 1

  jackson:
    time-zone: Asia/Kolkata

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.time_zone: Asia/Kolkata

server:
  port: 8050
