server:
  port: 8070
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:postgresql://ms_pg_sql:5432/ecommerce
    username: venom
    password: venom
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect



management:
  endpoints:
    web:
      exposure:
        include: health,info

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.apache.kafka: INFO

eureka:
  client:
    service-url:
      defaultZone: http://eureka-discovery:8761/eureka